name: Angular Tests

on:
  push:
    branches:
      - main

jobs:
  angular-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.12.2'

      - name: Install dependencies
        run: npm install

      - name: Run Angular tests
        run: ng test --watch=false
